// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorial: [
    'intro',
    {
      '开始': [
        {
          type: 'autogenerated',
          dirName: 'guide/start',
        },
      ],
    },
    {
      '使用': [
        {
          type: 'autogenerated',
          dirName: 'guide/tutorial',
        },
      ],
    },
    {
      '迁移': [
        {
          type: 'autogenerated',
          dirName: 'guide/migrate',
        },
      ],
    },
    'guide/question',
  ],
  manual: [
    'manual/index',
    {
      '起步': [
        {
          type: 'autogenerated',
          dirName: 'manual/basic',
        },
      ],
    },
    {
      '深入': [
        {
          type: 'autogenerated',
          dirName: 'manual/depth',
        },
      ],
    },
    {
      '进阶': [
        {
          type: 'autogenerated',
          dirName: 'manual/advanced',
        },
      ],
    },
    {
      '扩展': [
        {
          type: 'autogenerated',
          dirName: 'manual/expand',
        },
      ],
    },
    'manual/glossary',
  ],
  api: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
  community: [
    {
      type: 'autogenerated',
      dirName: 'community',
    },
  ],
}

module.exports = sidebars
