name: Dependency Review

on:
  pull_request_target:
    branches:
      - main
    paths:
      - package.json

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
