name: Lighthouse Report

on:
  pull_request_target:
    branches:
      - main
    paths:
      - "src/**"
      - "docs/**"
      - "static/**"
      - "package.json"
      - "babel.config.js"
      - "docusaurus.config.js"
      - "sidebars.js"
      - "unocss.config.ts"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lighthouse-report:
    permissions:
      pull-requests: write
    name: Lighthouse Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Yarn install
        uses: ./.github/actions/yarn-nm-install
        with:
          enable-corepack: true

      - name: Build Doc
        run: yarn build

      - name: Audit URLs using Lighthouse
        id: lighthouse_audit
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            http://localhost:3000
            http://localhost:3000/docs/intro
          configPath: ./.github/workflows/lighthouserc.json
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Format lighthouse score
        id: format_lighthouse_score
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const results = ${{ steps.lighthouse_audit.outputs.manifest }}
            const links = ${{ steps.lighthouse_audit.outputs.links }}
            const createLighthouseReport = (await import(`${process.env.GITHUB_WORKSPACE}/scripts/formatLighthouseReport.js`)).default;
            return createLighthouseReport({ results, links });

      - name: Add Lighthouse stats as comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.pull_request.number }}
          header: lighthouse
          message: ${{ steps.format_lighthouse_score.outputs.result }}
