name: Lint

on:
  pull_request:
    paths:
      - "src/**"
      - "docs/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Yarn install
        uses: ./.github/actions/yarn-nm-install
        with:
          enable-corepack: true

      - name: Lint
        run: yarn lint && yarn lint:style

      - name: Prettier Code
        run: yarn format:diff
